// <auto-generated />
using System;
using APIChallenge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIChallenge.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20221020123640_AddOwnTable")]
    partial class AddOwnTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("APIChallenge.Data.Empregado", b =>
                {
                    b.Property<int>("id_empregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Projetoid_projeto")
                        .HasColumnType("int");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("primeiro_nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("telefone")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("ultimo_nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_empregado");

                    b.HasIndex("Projetoid_projeto");

                    b.ToTable("Empregados");

                    b.HasData(
                        new
                        {
                            id_empregado = 1,
                            endereco = "joaoneivanetos@gmail.com",
                            primeiro_nome = "Joao",
                            telefone = 1111111111,
                            ultimo_nome = "Neto"
                        });
                });

            modelBuilder.Entity("APIChallenge.Data.Projeto", b =>
                {
                    b.Property<int>("id_projeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("data_de_criação")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("data_temino")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("gerente")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_projeto");

                    b.HasIndex("gerente");

                    b.ToTable("Projetos");

                    b.HasData(
                        new
                        {
                            id_projeto = 1,
                            data_de_criação = new DateTime(2022, 10, 20, 9, 36, 38, 338, DateTimeKind.Local).AddTicks(8227),
                            data_temino = new DateTime(2022, 10, 20, 9, 36, 38, 339, DateTimeKind.Local).AddTicks(7720),
                            gerente = 1,
                            nome = "Leonardo"
                        });
                });

            modelBuilder.Entity("APIChallenge.Data.Empregado", b =>
                {
                    b.HasOne("APIChallenge.Data.Projeto", null)
                        .WithMany("empregados")
                        .HasForeignKey("Projetoid_projeto");
                });

            modelBuilder.Entity("APIChallenge.Data.Projeto", b =>
                {
                    b.HasOne("APIChallenge.Data.Empregado", "empregado")
                        .WithMany("projetos")
                        .HasForeignKey("gerente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("empregado");
                });

            modelBuilder.Entity("APIChallenge.Data.Empregado", b =>
                {
                    b.Navigation("projetos");
                });

            modelBuilder.Entity("APIChallenge.Data.Projeto", b =>
                {
                    b.Navigation("empregados");
                });
#pragma warning restore 612, 618
        }
    }
}
