// <auto-generated />
using APIChallenge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIChallenge.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20221018174341_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("APIChallenge.Data.Empregado", b =>
                {
                    b.Property<int>("id_empregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("primeiro_nome")
                        .HasColumnType("longtext");

                    b.Property<int>("telefone")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("ultimo_nome")
                        .HasColumnType("longtext");

                    b.HasKey("id_empregado");

                    b.ToTable("Empregados");

                    b.HasData(
                        new
                        {
                            id_empregado = 1,
                            endereco = "joaoneivanetos@gmail.com",
                            primeiro_nome = "Joao",
                            telefone = 1111111111,
                            ultimo_nome = "Neto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
